# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget caffe proto)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target caffe
add_library(caffe SHARED IMPORTED)

set_target_properties(caffe PROPERTIES
  INTERFACE_LINK_LIBRARIES "proto;proto;/root/anaconda3/envs/caffe/lib/libboost_system.so;/root/anaconda3/envs/caffe/lib/libboost_thread.so;-lpthread;/root/anaconda3/envs/caffe/lib/libboost_filesystem.so;/root/anaconda3/envs/caffe/lib/libboost_regex.so;/root/anaconda3/envs/caffe/lib/libboost_chrono.so;/root/anaconda3/envs/caffe/lib/libboost_date_time.so;/root/anaconda3/envs/caffe/lib/libboost_atomic.so;-lpthread;/root/anaconda3/envs/caffe/lib/libglog.so;/root/anaconda3/envs/caffe/lib/libgflags.so;/root/anaconda3/envs/caffe/lib/libprotobuf.so;-lpthread;/root/anaconda3/envs/caffe/lib/libhdf5_cpp.so;/root/anaconda3/envs/caffe/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/root/anaconda3/envs/caffe/lib/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so;/root/anaconda3/envs/caffe/lib/libhdf5_hl_cpp.so;/root/anaconda3/envs/caffe/lib/libhdf5_hl.so;/root/anaconda3/envs/caffe/lib/liblmdb.so;/root/anaconda3/envs/caffe/lib/libleveldb.so;/root/anaconda3/envs/caffe/lib/libsnappy.so;/root/anaconda3/envs/caffe/lib/libturbojpeg.so.0;/usr/local/cuda/lib64/libcudart.so;/usr/local/cuda/lib64/libcurand.so;/usr/lib/x86_64-linux-gnu/libcublas.so;/usr/lib/x86_64-linux-gnu/libcudnn.so;opencv_imgcodecs;opencv_core;opencv_imgcodecs;opencv_highgui;opencv_imgproc;opencv_videoio;/root/anaconda3/envs/caffe/lib/libopenblas.so;/root/anaconda3/envs/caffe/lib/libboost_python27.so;/root/anaconda3/envs/caffe/lib/libpython2.7.so;/usr/lib/x86_64-linux-gnu/libnccl.so;/usr/local/cuda/lib64/stubs/libnvidia-ml.so"
)

# Create imported target proto
add_library(proto STATIC IMPORTED)

# Import target "caffe" for configuration "Release"
set_property(TARGET caffe APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(caffe PROPERTIES
  IMPORTED_LOCATION_RELEASE "/workspace/caffe-jacinto/lib/libcaffe-nv.so.0.17.0"
  IMPORTED_SONAME_RELEASE "libcaffe-nv.so.0.17"
  )

# Import target "proto" for configuration "Release"
set_property(TARGET proto APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(proto PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/caffe-jacinto/lib/libproto.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
